AWSTemplateFormatVersion: '2010-09-09'
Description: 'NYC Taxi Project Infrastructure'

Parameters:
  ProjectName:
    Type: String
    Default: nyc-taxi
    Description: Prefix for S3 buckets
    
  Env:
    Type: String
    Default: dev
    AllowedValues: [dev, stg, prod]
    Description: Environment name to include in bucket names
  
  DeployStepFunction:
    Type: String
    Default: 'false'
    AllowedValues: ['true', 'false']

Conditions:
  CreateSF: !Equals [!Ref DeployStepFunction, 'true' ]  


Resources:
  # --- Storage Layer: S3 Buckets --- #
  RawBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub '${ProjectName}-${Env}-raw-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256 # Use AES256 (SSE-S3) or aws:kms (SSE-KMS)
  
  ProcessedBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub '${ProjectName}-${Env}-processed-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  CuratedBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub '${ProjectName}-${Env}-curated-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  MasterBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub '${ProjectName}-${Env}-master-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  # --- 2. Metadata Layer: Glue Catalog --- #
  GlueCatalogDatabase:
    Type: 'AWS::Glue::Database'
    Properties:
      CatalogId: !Ref 'AWS::AccountId'
      DatabaseInput:
        Name: !Sub '${ProjectName}_${Env}_db'

  # This Crawler scans the CSVs in the Raw bucket and creates the Catalog Table
  RawDataCrawler:
    Type: 'AWS::Glue::Crawler'
    Properties:
      Name: !Sub '${ProjectName}-${Env}-raw-csv-crawler'
      Role: !GetAtt GlueServiceRoleNew.Arn
      DatabaseName: !Ref GlueCatalogDatabase
      Targets:
        S3Targets:
          - Path: !Sub 's3://${ProjectName}-${Env}-raw-${AWS::AccountId}/landing_files/'
      TablePrefix: 'raw_'
      SchemaChangePolicy:
        UpdateBehavior: 'UPDATE_IN_DATABASE'
        DeleteBehavior: 'LOG'

  # --- Compute Layer: IAM Role for AWS Glue --- #
  GlueServiceRoleNew:
    Type: 'AWS::IAM::Role'
    DeletionPolicy: Retain
    DependsOn: 
      - RawBucket
      - ProcessedBucket
      - CuratedBucket
      - MasterBucket
    Properties:
      Path: /service-role/
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [glue.amazonaws.com]
            Action: ['sts:AssumeRole']
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: S3DataLakeAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # Permissions for the S3
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:PutObject'
                  - 's3:DeleteObject'
                  - 's3:ListBucket'
                Resource:
                  - !Sub 'arn:aws:s3:::${ProjectName}-${Env}-*-${AWS::AccountId}'
                  - !Sub 'arn:aws:s3:::${ProjectName}-${Env}-*-${AWS::AccountId}/*'
              # Permissions for the Crawler to create/update tables
              - Effect: Allow
                Action:
                  - 'glue:CreateTable'
                  - 'glue:UpdateTable'
                  - 'glue:GetTable'
                  - 'glue:GetDatabase'
                Resource:
                  - !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:catalog'
                  - !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/${ProjectName}_${Env}_db'
                  - !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:table/${ProjectName}_${Env}_db/*'

  StepFunctionExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: StepFunctionGlueAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'glue:StartCrawler'
                  - 'glue:GetCrawler'
                  - 'glue:StartJobRun'
                  - 'glue:GetJobRun'
                  - 'glue:GetJobRuns'
                  - 'glue:BatchGetJobs'
                Resource: '*' # Or narrow down to your specific Job/Crawler ARNs
                # Permissions to send logsto CloudWatch
              - Effect: Allow
                Action:
                  - "logs:CreateLogDelivery"
                  - "logs:GetLogDelivery"
                  - "logs:UpdateLogDelivery"
                  - "logs:DeleteLogDelivery"
                  - "logs:ListLogDeliveries"
                  - "logs:PutLogEvents"
                  - "logs:PutResourcePolicy"
                  - "logs:DescribeResourcePolicies"
                  - "logs:DescribeLogGroups"
                Resource: "*"

  # --- ETL Layer: AWS Glue Job --- #
  RawToProcessedJob:
    Type: 'AWS::Glue::Job'
    Properties:
      Name: !Sub '${ProjectName}-${Env}-raw-to-processed-job'
      Role: !GetAtt GlueServiceRoleNew.Arn
      GlueVersion: '3.0'
      Command:
        Name: glueetl
        ScriptLocation: !Sub 's3://${ProjectName}-${Env}-raw-${AWS::AccountId}/scripts/glue/raw_to_processed.py'
      ExecutionProperty:
        MaxConcurrentRuns: 1
      MaxRetries: 0  # <--- Set to 0 to save credits on failure
      DefaultArguments:
        # These map directly to the sys.argv in your PySpark script
        '--JOB_NAME': !Sub '${ProjectName}-${Env}-raw-to-processed-job'
        '--RAW_TABLE_NAME': 'raw_landing_files'
        '--CATALOG_DB': !Sub '${ProjectName}_${Env}_db'
        '--SQL_DIR': !Sub 's3://${ProjectName}-${Env}-raw-${AWS::AccountId}/scripts/sql/'
        '--PROCESSED_PATH': !Sub 's3://${ProjectName}-${Env}-processed-${AWS::AccountId}/processed_files/'
        # Enables Delta Lake format support
        '--datalake-formats': 'delta'
        # Required Spark configuration for Delta extensions
        '--conf': 'spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog'
        # Logging and performance defaults
        '--enable-continuous-cloudwatch-log': 'true' # Real-time text logs
        '--enable-metrics': 'true'                   # Basic CloudWatch metrics
        '--enable-observability-metrics': 'true'     # Advanced visual monitoring
        '--job-bookmark-option': 'job-bookmark-enable'
      MaxCapacity: 2.0
      Timeout: 5

  # --- ETL Layer: AWS Glue Job --- # 
  NycTaxiStateMachine:
    Type: 'AWS::StepFunctions::StateMachine'
    DependsOn: 
      - StepFunctionExecutionRole
    Condition: CreateSF
    Properties:
      StateMachineName: !Sub '${ProjectName}-${Env}-sf'
      RoleArn: !GetAtt StepFunctionExecutionRole.Arn
      # Use DefinitionSubstitutions to pass dynamic values into your JSON file
      DefinitionSubstitutions:
        CrawlerName: !Ref RawDataCrawler
        GlueJobName: !Ref RawToProcessedJob
      # This reads the JSON logic from s3 
      DefinitionS3Location:
        Bucket: !Ref RawBucket
        Key: 'sf_scripts/nyc-taxi-sf.json'


Outputs:
  RawBucketName:
    Value: !Ref RawBucket
  ProcessedBucketName:
    Value: !Ref ProcessedBucket
  GlueDatabaseName:
    Value: !Ref GlueCatalogDatabase
  GlueJobName:
    Value: !Ref RawToProcessedJob
  StateMachineArn:
    Value: !Ref NycTaxiStateMachine
    Condition: CreateSF

