AWSTemplateFormatVersion: '2010-09-09'
Description: 'NYC Taxi Project Infrastructure'

Parameters:
  ProjectName:
    Type: String
    Default: nyc-taxi
    Description: Prefix for S3 buckets
    
  Env:
    Type: String
    Default: dev
    AllowedValues: [dev, stg, prod]
    Description: Environment name to include in bucket names
  
  DeployStepFunction:
    Type: String
    Default: 'false'
    AllowedValues: ['true', 'false']

Conditions:
  CreateSF: !Equals [!Ref DeployStepFunction, 'true' ]  


Resources:
  # ==== 1. S3 Buckets ==== #
  RawBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub '${ProjectName}-${Env}-raw-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256 # Use AES256 (SSE-S3) or aws:kms (SSE-KMS)
      LifecycleConfiguration:
        Rules:
          - Id: AutoDeleteAthenaResults
            Status: Enabled
            Prefix: athena_results/
            ExpirationInDays: 7
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true
  
  ProcessedBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub '${ProjectName}-${Env}-processed-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  CuratedBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub '${ProjectName}-${Env}-curated-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  MasterBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub '${ProjectName}-${Env}-master-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true

  # ==== 2.1. Metadata Layer: Glue Catalog ==== #
  GlueCatalogDatabase:
    Type: 'AWS::Glue::Database'
    Properties:
      CatalogId: !Ref 'AWS::AccountId'
      DatabaseInput:
        Name: !Sub '${ProjectName}_${Env}_db'

  # ==== 2.2. Glue Crawler ==== #
  RawDataCrawler:
    Type: 'AWS::Glue::Crawler'
    Properties:
      Name: !Sub '${ProjectName}-${Env}-raw-csv-crawler'
      Role: !GetAtt GlueServiceRoleNew.Arn
      DatabaseName: !Ref GlueCatalogDatabase
      Targets:
        S3Targets:
          - Path: !Sub 's3://${ProjectName}-${Env}-raw-${AWS::AccountId}/landing_files/'
      TablePrefix: 'raw_'
      SchemaChangePolicy:
        UpdateBehavior: 'UPDATE_IN_DATABASE'
        DeleteBehavior: 'LOG'

  # ==== 3.1. IAM Role for Glue ==== #
  GlueServiceRoleNew:
    Type: 'AWS::IAM::Role'
    DeletionPolicy: Retain
    DependsOn: 
      - RawBucket
      - ProcessedBucket
      - CuratedBucket
      - MasterBucket
    Properties:
      Path: /service-role/
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [glue.amazonaws.com]
            Action: ['sts:AssumeRole']
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: S3DataLakeAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # Permissions for the S3
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:PutObject'
                  - 's3:DeleteObject'
                  - 's3:ListBucket'
                Resource:
                  - !Sub 'arn:aws:s3:::${ProjectName}-${Env}-*-${AWS::AccountId}'
                  - !Sub 'arn:aws:s3:::${ProjectName}-${Env}-*-${AWS::AccountId}/*'
              # Permissions for the Crawler to create/update tables
              - Effect: Allow
                Action:
                  - 'glue:CreateTable'
                  - 'glue:UpdateTable'
                  - 'glue:GetTable'
                  - 'glue:GetDatabase'
                Resource:
                  - !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:catalog'
                  - !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/${ProjectName}_${Env}_db'
                  - !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:table/${ProjectName}_${Env}_db/*'
              # Permissions to call and run Athena queries
              - Effect: Allow
                Action:
                  - athena:StartQueryExecution
                  - athena:GetQueryExecution
                  - athena:GetQueryResults
                Resource: "*"

  # ==== 3.2. IAM Role for Step Function ==== #
  StepFunctionExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: StepFunctionGlueAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # Permissions to trigger Glue
              - Effect: Allow
                Action:
                  - 'glue:StartCrawler'
                  - 'glue:GetCrawler'
                  - 'glue:StartJobRun'
                  - 'glue:GetJobRun'
                  - 'glue:GetJobRuns'
                  - 'glue:BatchGetJobs'
                Resource: '*' 
                # Permissions to send logs to CloudWatch
              - Effect: Allow
                Action:
                  - "logs:CreateLogDelivery"
                  - "logs:GetLogDelivery"
                  - "logs:UpdateLogDelivery"
                  - "logs:DeleteLogDelivery"
                  - "logs:ListLogDeliveries"
                  - "logs:PutLogEvents"
                  - "logs:PutResourcePolicy"
                  - "logs:DescribeResourcePolicies"
                  - "logs:DescribeLogGroups"
                Resource: "*"
        # Permissions for Sf to trigger SNS (moved to eventbridge rule - not required)
        - !If
          - CreateSF        
          - PolicyName: SNSPublishPolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action: "sns:Publish"
                  Resource: !Ref NycTaxiSfErrorTopic
          - !Ref "AWS::NoValue" # Do ntg if cond is false

  # ==== 3.3 IAM Role for EventBridge ==== #
  EventBridgeExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:     
        - PolicyName: EventbridgeRules
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              # Permissions to trigger Step Functions         
              - Effect: Allow
                Action: states:StartExecution
                Resource: !If [CreateSF, !Ref NycTaxiStateMachine, "arn:aws:states:*:*:stateMachine:*"]
              # Permissions to trigger Glue Job
              - Effect: Allow
                Action: glue:StartJobRun
                Resource: !Sub "arn:${AWS::Partition}:glue:${AWS::Region}:${AWS::AccountId}:job/${LookupToMasterJob}"

  # ==== 3.4 Resource Policy ==== #
  SnsTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Condition: CreateSF
    Properties:
      Topics:
        - !Ref NycTaxiSfErrorTopic
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          # Permission for EventBridge to Publish to SNS
          - Effect: Allow
            Principal:
              Service: "events.amazonaws.com"
            Action: "sns:Publish"
            Resource: !Ref NycTaxiSfErrorTopic

  # ==== 4. ETL Layer: AWS Glue Jobs ==== #
  RawToProcessedJob:
    Type: 'AWS::Glue::Job'
    Properties:
      Name: !Sub '${ProjectName}-${Env}-raw-to-processed-job'
      Role: !GetAtt GlueServiceRoleNew.Arn
      GlueVersion: "4.0"
      NumberOfWorkers: 2
      WorkerType: G.1X
      Command:
        Name: glueetl
        ScriptLocation: !Sub 's3://${ProjectName}-${Env}-raw-${AWS::AccountId}/scripts/glue/raw_to_processed.py'
      ExecutionProperty:
        MaxConcurrentRuns: 1
      MaxRetries: 0  # Set to 0 to save credits on failure
      Timeout: 5
      DefaultArguments:
        # These map to the sys.argv in PySpark script
        '--JOB_NAME': 'raw-to-processed'
        '--RAW_TABLE_NAME': 'raw_landing_files'
        '--CATALOG_DB': !Sub '${ProjectName}_${Env}_db'
        '--SQL_DIR': !Sub 's3://${ProjectName}-${Env}-raw-${AWS::AccountId}/scripts/sql/'
        '--PROCESSED_PATH': !Sub 's3://${ProjectName}-${Env}-processed-${AWS::AccountId}/processed_files/'
        "--RAW_BUCKET": !Ref RawBucket
        '--datalake-formats': 'delta'
        # Required Spark configuration for Delta extensions
        '--conf': 'spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog'
        # Logging and performance defaults
        '--enable-continuous-cloudwatch-log': 'true' # Real-time text logs
        '--enable-metrics': 'true'                   # Basic CloudWatch metrics
        '--enable-observability-metrics': 'true'     # Advanced visual monitoring
        '--job-bookmark-option': 'job-bookmark-enable'
  
  LookupToMasterJob:
    Type: AWS::Glue::Job
    Properties:
      Name: !Sub '${ProjectName}-${Env}-lookup-to-master-job'
      Role: !GetAtt GlueServiceRoleNew.Arn
      GlueVersion: "4.0"
      NumberOfWorkers: 2
      WorkerType: G.1X
      Command:
        Name: glueetl
        ScriptLocation: !Sub 's3://${ProjectName}-${Env}-raw-${AWS::AccountId}/scripts/glue/lookup_to_master.py'
      ExecutionProperty:
        MaxConcurrentRuns: 1
      MaxRetries: 0
      Timeout: 5
      DefaultArguments:
        '--JOB_NAME': 'lookup-to-master'
        "--RAW_BUCKET": !Ref RawBucket
        "--MASTER_BUCKET": !Ref MasterBucket
        "--CATALOG_DB": !Sub '${ProjectName}_${Env}_db'
        "--SOURCE_CSV": "lookup_files/taxi_zone_lookup.csv"
        "--SNS_TOPIC_ARN": !Ref StewardReviewTopic
        "--datalake-formats": "delta"
        "--additional-python-modules": "fuzzywuzzy,python-Levenshtein"
        '--enable-continuous-cloudwatch-log': 'true' 
        '--enable-metrics': 'true'                   
        '--enable-observability-metrics': 'true' 
        '--job-bookmark-option': 'job-bookmark-enable'
        "--conf": "spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog"

  StewardReviewJob:
    Type: AWS::Glue::Job
    Properties:
      Name: !Sub "${ProjectName}-${Env}-steward-review-job"
      Role: !GetAtt GlueServiceRoleNew.Arn
      GlueVersion: "4.0"
      NumberOfWorkers: 2
      WorkerType: G.1X
      Command:
        Name: glueetl
        ScriptLocation: !Sub "s3://${ProjectName}-${Env}-raw-${AWS::AccountId}/scripts/glue/steward_review.py"
      DefaultArguments:
        "--MASTER_BUCKET": !Ref MasterBucket
        "--CATALOG_DB": !Sub "${ProjectName}_${Env}_db"

  ProcessedToCuratedJob:
    Type: AWS::Glue::Job
    Properties:
      Name: !Sub '${ProjectName}-${Env}-processed-to-curated-job'
      Role: !GetAtt GlueServiceRoleNew.Arn
      GlueVersion: "4.0"
      NumberOfWorkers: 2
      WorkerType: G.1X
      Command:
        Name: glueetl
        ScriptLocation: !Sub 's3://${ProjectName}-${Env}-raw-${AWS::AccountId}/scripts/glue/processed_to_curated.py'
      ExecutionProperty:
        MaxConcurrentRuns: 1
      MaxRetries: 0
      Timeout: 5
      DefaultArguments:
        '--JOB_NAME': 'processed-to-curated'
        "--RAW_BUCKET": !Ref RawBucket
        "--PROCESSED_BUCKET": !Ref ProcessedBucket
        "--MASTER_BUCKET": !Ref MasterBucket
        "--CURATED_BUCKET": !Ref CuratedBucket
        "--CATALOG_DB": !Sub '${ProjectName}_${Env}_db'
        "--datalake-formats": "delta"
        '--enable-continuous-cloudwatch-log': 'true'
        '--enable-metrics': 'true'                   
        '--enable-observability-metrics': 'true'     
        '--job-bookmark-option': 'job-bookmark-enable'
        "--conf": "spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog"

  # SNS Topic for Steward Review
  StewardReviewTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${ProjectName}-${Env}-steward-review"

  # SNS Subscription for Steward Review
  StewardEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref StewardReviewTopic
      Protocol: email
      Endpoint: "tkavita.kavs@gmail.com"

  # ==== 5. Athena ==== #
  AthenaNycTaxiWorkgroup:
    Type: AWS::Athena::WorkGroup
    Properties:
      Name: nyc_taxi_workgroup
      Description: "Athena Workgroup for NYC Taxi Dev"
      State: ENABLED
      WorkGroupConfiguration:
        ResultConfiguration:
          OutputLocation: !Sub "s3://${RawBucket}/athena_results/"
        EnforceWorkGroupConfiguration: true # This overrides user console settings

  # ==== 5. Step Function ==== # 
  NycTaxiStateMachine:
    Type: 'AWS::StepFunctions::StateMachine'
    DependsOn: 
      - StepFunctionExecutionRole
    Condition: CreateSF
    Properties:
      StateMachineName: !Sub '${ProjectName}-${Env}-sf'
      RoleArn: !GetAtt StepFunctionExecutionRole.Arn
      # To pass dynamic values into Step Function JSON
      DefinitionSubstitutions:
        CrawlerName: !Ref RawDataCrawler
        GlueJobName1: !Ref RawToProcessedJob
        GlueJobName2: !Ref ProcessedToCuratedJob
      # To read the JSON from s3 
      DefinitionS3Location:
        Bucket: !Ref RawBucket
        Key: 'sf_scripts/nyc-taxi-sf.json'

  # ==== 6.1 EventBridge : Trigger SF on S3 Upload ==== #
  S3ToStepFunctionRule:
    Type: AWS::Events::Rule
    Condition: CreateSF
    Properties:
      Description: "Trigger SF when file is uploaded to raw_bucket/landing_files/"
      State: ENABLED
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - "Object Created"
        detail:
          bucket:
            name:
              - !Sub '${ProjectName}-${Env}-raw-${AWS::AccountId}'
          object:
            key:
              - prefix: "landing_files/"  # Filter for file path
      Targets:
        - Arn: !Ref NycTaxiStateMachine
          Id: "NycTaxiSfTarget"
          RoleArn: !GetAtt EventBridgeExecutionRole.Arn

  # ==== 6.2 EventBridge : SF Failure ==== #
  StepFunctionFailureRule:
    Type: AWS::Events::Rule
    Condition: CreateSF
    Properties:
      Description: "Trigger SNS if NYC Taxi Step Function fails"
      State: ENABLED
      EventPattern:
        source:
          - "aws.states"
        detail-type:
          - "Step Functions Execution Status Change"
        detail:
          status:
            - "FAILED"
            - "TIMED_OUT"
            - "ABORTED"
          stateMachineArn:
            - !Ref NycTaxiStateMachine
      Targets:
        - Arn: !Ref NycTaxiSfErrorTopic
          Id: "SendToSNS"

  # ==== 6.3 EventBridge : Trigger Master Job on CSV upload ==== #
  S3ToMasterJobRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Trigger Master Glue Job when lookup CSV is uploaded"
      State: ENABLED
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - "Object Created"
        detail:
          bucket:
            name:
              - !Sub '${ProjectName}-${Env}-master-${AWS::AccountId}'
          object:
            key:
              - prefix: "lookup_files/" 
      Targets:
        - Arn: !Sub "arn:${AWS::Partition}:glue:${AWS::Region}:${AWS::AccountId}:job/${LookupToMasterJob}"
          Id: "MasterJobTarget"
          RoleArn: !GetAtt EventBridgeExecutionRole.Arn

  # ==== 7.1. SNS Topic for SF Failure ==== #
  NycTaxiSfErrorTopic:
    Type: AWS::SNS::Topic
    Condition: CreateSF
    Properties:
      TopicName: !Sub "${ProjectName}-error-notifications"

  # ==== 7.2. SNS Email Subscription for SF Failure ==== #
  NycTaxiEmailSubscription:
    Type: AWS::SNS::Subscription
    Condition: CreateSF
    Properties:
      Endpoint: "tkavita.kavs@gmail.com"
      Protocol: email
      TopicArn: !Ref NycTaxiSfErrorTopic

  # ==== 8.1. Cloudwatch Alarm : SF Failure ==== # 
  StepFunctionFailedAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: CreateSF
    Properties:
      AlarmDescription: "Alarm for the NYC Taxi Pipeline failure"
      Namespace: "AWS/States"
      MetricName: "ExecutionsFailed"
      Dimensions:
        - Name: "StateMachineArn"
          Value: !Ref NycTaxiStateMachine
      Statistic: "Sum"
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: "GreaterThanOrEqualToThreshold"
      AlarmActions:
        - !Ref NycTaxiSfErrorTopic

  # ==== 8.2. Cloudwatch Monitoring ==== #
  CloudwatchDashboard:
    Type: AWS::CloudWatch::Dashboard
    Condition: CreateSF
    Properties:
      DashboardName: !Sub "${ProjectName}-Monitoring"
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "x": 0, "y": 0, "width": 12, "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/States", "ExecutionsSucceeded", "StateMachineArn", "${NycTaxiStateMachine}" ],
                  [ ".", "ExecutionsFailed", ".", "." ]
                ],
                "period": 300,
                "stat": "Sum",
                "region": "${AWS::Region}",
                "title": "Pipeline Success vs Failure"
              }
            }
          ]
        }
  
Outputs:
  RawBucketName:
    Value: !Ref RawBucket
  ProcessedBucketName:
    Value: !Ref ProcessedBucket
  MasterBucketName:
    Value: !Ref MasterBucket
  CuratedBucketName:
    Value: !Ref CuratedBucket
  GlueDatabaseName:
    Value: !Ref GlueCatalogDatabase
  MasterGlueJob:
    Value: !Ref LookupToMasterJob
  GlueJobName1:
    Value: !Ref RawToProcessedJob
  GlueJobName2:
    Value: !Ref ProcessedToCuratedJob
  StateMachineArn:
    Value: !Ref NycTaxiStateMachine
    Condition: CreateSF

