AWSTemplateFormatVersion: '2010-09-09'
Description: 'NYC Taxi Project Infrastructure'

Parameters:
  ProjectName:
    Type: String
    Default: nyc-taxi
    Description: Prefix for S3 buckets
    
  Env:
    Type: String
    Default: dev
    AllowedValues: [dev, stg, prod]
    Description: Environment name to include in bucket names

Resources:
  # --- Storage Layer: S3 Buckets --- #
  RawBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${ProjectName}-${Env}-raw-${AWS::AccountId}'
  
  ProcessedBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${ProjectName}-${Env}-processed-${AWS::AccountId}'

  CuratedBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${ProjectName}-${Env}-curated-${AWS::AccountId}'

  MasterBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${ProjectName}-${Env}-master-${AWS::AccountId}'

  # --- Compute Layer: IAM Role for AWS Glue --- #
  GlueServiceRoleNew:
    Type: 'AWS::IAM::Role'
    DeletionPolicy: Retain
    DependsOn: 
      - RawBucket
      - ProcessedBucket
      - CuratedBucket
      - MasterBucket
    Properties:
      Path: /service-role/
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [glue.amazonaws.com]
            Action: ['sts:AssumeRole']
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: S3DataLakeAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:PutObject'
                  - 's3:DeleteObject'
                  - 's3:ListBucket'
                Resource:
                  - !Sub 'arn:aws:s3:::${ProjectName}-${Env}-*-${AWS::AccountId}'
                  - !Sub 'arn:aws:s3:::${ProjectName}-${Env}-*-${AWS::AccountId}/*'
